class PngImport:
    def __init__(self):
        self.icon = "../ball/chesspy/chess_icon.ico"
        self.black_bishop = "../ball/chesspy/chess_set_1/Chess_bdt60.png"
        self.black_king = "../ball/chesspy/chess_set_1/Chess_kdt60.png"
        self.black_knight = "../ball/chesspy/chess_set_1/Chess_ndt60.png"
        self.black_pawn = "../ball/chesspy/chess_set_1/Chess_pdt60.png"
        self.black_queen = "../ball/chesspy/chess_set_1/Chess_qdt60.png"
        self.black_rook = "../ball/chesspy/chess_set_1/Chess_rdt60.png"
        self.white_bishop = "../ball/chesspy/chess_set_1/Chess_blt60.png"
        self.white_king = "../ball/chesspy/chess_set_1/Chess_klt60.png"
        self.white_knight = "../ball/chesspy/chess_set_1/Chess_nlt60.png"
        self.white_pawn = "../ball/chesspy/chess_set_1/Chess_plt60.png"
        self.white_queen = "../ball/chesspy/chess_set_1/Chess_qlt60.png"
        self.white_rook = "../ball/chesspy/chess_set_1/Chess_rlt60.png"
        self.board = "../ball/chesspy/chess_board_1.png"
        self.main_menu = "../ball/chesspy/main_menu.png"